POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lNCIsImlkIjoiNyIsImlhdCI6MTYyNTA1ODAyNH0.SYrzqxbQL0Temrpuibi4PBgJg2uDqRBWeuH17b6kagk

{
    "title": "authorized blog title",
    "content": "authorized content"
}

#####################

GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

######################

GET http://localhost:3001/api/blogs/1 HTTP/1.1
content-type: application/json

############################

DELETE http://localhost:3001/api/blogs/2 HTTP/1.1
content-type: application/json

############################


POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "newusername4",
    "password": "newpassword"
}

############################

GET http://localhost:3001/api/users/1 HTTP/1.1
content-type: application/json

############################

POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "newusername4",
    "password": "newpassword"
}

############################