POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "blog 1",
    "content": "content 1"
}

#####################

GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

######################

GET http://localhost:3001/api/blogs/60a3c423fa6ffa74c287cad8 HTTP/1.1
content-type: application/json

############################