POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjBhN2JjNDA5ZTAyZGE2MzZhYWIwNzhjIiwiaWF0IjoxNjIyMDA1MDY0fQ.QqXPzTBoKGna56xDSYf_W-4tlREtsAdLwoncF-yqGgA

{
    "title": "authorized blog title",
    "content": "authorized content"
}

#####################

GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

######################

GET http://localhost:3001/api/blogs/60ade3949afce2339446f13c HTTP/1.1
content-type: application/json

############################

DELETE http://localhost:3001/api/blogs/60ade15e197cc531614999fe HTTP/1.1
content-type: application/json

############################


POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "username1",
    "password": "pasdasdasdasd"
}

############################

GET http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

############################

POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "username1",
    "password": "pasdasdasdasd"
}

############################